In [1]:
using Revise
using DrWatson
@quickactivate "ABoxWorld"
include(srcdir("ABoxWorld.jl"));

┌ Error: This code is meant to be used in the ABoxWorld project. Please activate the ABoxWorld project by "@quickactivate ABoxWorld" before using this code
└ @ Main s:\Sync\University\2023_MRP_2\MRP2_WorkDir\ABoxWorld\src\ABoxWorld_core.jl:5
    CondaPkg Found dependencies: s:\Sync\University\2023_MRP_2\MRP2_WorkDir\ABoxWorld\CondaPkg.toml
    CondaPkg Found dependencies: C:\Users\trothe\.julia\packages\PythonCall\wXfah\CondaPkg.toml
    CondaPkg Found dependencies: C:\Users\trothe\.julia\environments\v1.10\CondaPkg.toml
    CondaPkg Found dependencies: C:\Users\trothe\.julia\packages\PythonPlot\KcWMF\CondaPkg.toml
    CondaPkg Removing environment
             │ C:\Users\trothe\.julia\artifacts\4b87dc8b933ca2d289a392e264aaf44df2410f6f\bin\micromamba.exe
             │ -r C:\Users\trothe\.julia\scratchspaces\0b3b1443-0f03-428d-bdfb-f27f9c1191ea\root
             │ remove
             │ -y
             │ -p s:\Sync\University\2023_MRP_2\MRP2_WorkDir\ABoxWorld\.CondaPkg\env
             

Transaction

  Prefix: S:\Sync\University\2023_MRP_2\MRP2_WorkDir\ABoxWorld\.CondaPkg\env

  Removing specs:

   - brotli
   - brotli-bin
   - bzip2
   - ca-certificates
   - certifi
   - contourpy
   - cycler
   - fonttools
   - freetype
   - gettext
   - glib
   - glib-tools
   - gst-plugins-base
   - gstreamer
   - icu
   - intel-openmp
   - kiwisolver
   - krb5
   - lcms2
   - lerc
   - libblas
   - libbrotlicommon
   - libbrotlidec
   - libbrotlienc
   - libcblas
   - libclang
   - libclang13
   - libdeflate
   - libexpat
   - libffi
   - libglib
   - libhwloc
   - libiconv
   - libjpeg-turbo
   - liblapack
   - libogg
   - libpng
   - libsqlite
   - libtiff
   - libvorbis
   - libwebp-base
   - libxcb
   - libxml2
   - libzlib
   - m2w64-gcc-libgfortran
   - m2w64-gcc-libs
   - m2w64-gcc-libs-core
   - m2w64-gmp
   - m2w64-libwinpthread-git
   - matplotlib
   - matplotlib-base
   - mkl
   - mpmath
   - msys2-conda-epoch
   - munkres
   - ncpol2sdpa
   - numpy
   - openjpeg
   - o

    CondaPkg Creating environment
             │ C:\Users\trothe\.julia\artifacts\4b87dc8b933ca2d289a392e264aaf44df2410f6f\bin\micromamba.exe
             │ -r C:\Users\trothe\.julia\scratchspaces\0b3b1443-0f03-428d-bdfb-f27f9c1191ea\root
             │ create
             │ -y
             │ -p s:\Sync\University\2023_MRP_2\MRP2_WorkDir\ABoxWorld\.CondaPkg\env
             │ --override-channels
             │ --no-channel-priority
             │ matplotlib[version='>=1']
             │ ncpol2sdpa[version='*']
             │ numpy[version='*']
             │ pip[version='>=22.0.0']
             │ python[version='>=3.7,<4',channel='conda-forge',build='*cpython*']
             └ -c conda-forge



Transaction

  Prefix: S:\Sync\University\2023_MRP_2\MRP2_WorkDir\ABoxWorld\.CondaPkg\env

  Updating specs:

   - matplotlib[version='>=1']
   - ncpol2sdpa=*
   - numpy=*
   - pip[version='>=22.0.0']
   - conda-forge::python[version='>=3.7,<4',build=*cpython*]


  Package                               Version  Build                  Channel           Size
------------------------------------------------------------------------------------------------
  Install:
------------------------------------------------------------------------------------------------

  + python_abi                             3.12  4_cp312                conda-forge     Cached
  + ucrt                           10.0.22621.0  h57928b3_0             conda-forge     Cached
  + libexpat                              2.6.1  h63175ca_0             conda-forge     Cached
  + ca-certificates                    2024.2.2  h56e8100_0             conda-forge     Cached
  + intel-openmp                       2024.0.0  h5792

    CondaPkg Installing Pip packages
             │ s:\Sync\University\2023_MRP_2\MRP2_WorkDir\ABoxWorld\.CondaPkg\env\Scripts\pip.exe
             │ install
             │ mosek
             │ ncpol2sdpa
             │ sdpa-python
             └ torch



Transaction finished

To activate this environment, use:

    micromamba activate S:\Sync\University\2023_MRP_2\MRP2_WorkDir\ABoxWorld\.CondaPkg\env

Or to execute a single command in this environment, use:

    micromamba run -p S:\Sync\University\2023_MRP_2\MRP2_WorkDir\ABoxWorld\.CondaPkg\env mycommand

  Using cached Mosek-10.1.27-cp37-abi3-win_amd64.whl.metadata (715 bytes)
  Using cached sdpa_python-0.2.1-cp312-cp312-win_amd64.whl.metadata (4.2 kB)
  Using cached torch-2.2.1-cp312-cp312-win_amd64.whl.metadata (26 kB)
  Using cached scipy-1.12.0-cp312-cp312-win_amd64.whl.metadata (60 kB)
  Using cached filelock-3.13.1-py3-none-any.whl.metadata (2.8 kB)
  Using cached typing_extensions-4.10.0-py3-none-any.whl.metadata (3.0 kB)
  Using cached networkx-3.2.1-py3-none-any.whl.metadata (5.2 kB)
  Using cached Jinja2-3.1.3-py3-none-any.whl.metadata (3.3 kB)
  Using cached fsspec-2024.2.0-py3-none-any.whl.metadata (6.8 kB)
  Using cached MarkupSafe-2.1.5-cp312-cp312-win_amd64.whl.metada

In [2]:
using LinearAlgebra
using Symbolics

#### Computing and displaying extremal wirings: 

In [3]:
all_extremal_wires = hcat(values(collect_all_extremal_wires())...)
nothing

In [4]:
collect(keys(collect_all_extremal_wires()))[rand(1:25)]

(:A, :O)

In [5]:
in1, out1 = wirings.in_out_split(collect_all_extremal_wires()[:X, :A][:,4])

([1.0 1.0; 0.0 0.0; 1.0 1.0; 0.0 0.0;;; 1.0 1.0; 0.0 0.0; 1.0 1.0; 0.0 0.0], [0.0 0.0; 0.0 0.0;;; 1.0 1.0; 0.0 0.0;;;; 1.0 1.0; 0.0 0.0;;; 0.0 0.0; 1.0 1.0])

In [6]:
in2, out2 = wirings.in_out_split(collect_all_extremal_wires()[:X, :A][:,8])

([1.0 1.0; 0.0 0.0; 1.0 1.0; 0.0 0.0;;; 1.0 1.0; 0.0 0.0; 1.0 1.0; 0.0 0.0], [1.0 1.0; 0.0 0.0;;; 0.0 0.0; 0.0 0.0;;;; 0.0 0.0; 0.0 0.0;;; 1.0 1.0; 1.0 1.0])

In [7]:

#wirings.print_functions_from_wires(all_extremal_wires[:,rand_idx])
wirings.print_functions_from_wires(collect_all_extremal_wires()[:X, :A][:,4])

f_1(x,a2) = 1.0 
g_1(y,b2) = 0
f_2(x,a1) = 1.0 
g_2(y,b1) = 0
f_3(x,a1,a2) = a1 ⊕ a2
g_3(y,b1,b2) = b1·b2


#### Bechmarking different method of computing BoxProduct:

In [8]:
using BenchmarkTools

function double_noisy_PRBox(;q1, q2)
    @assert 0.0 - 10*eps() <= q1 <= 1.0 + 10*eps() 
    @assert 0.0 - 10*eps() <= q2 <= 1.0 + 10*eps()
    @assert q1 + q2 <= 1.0 + 100*eps()
    @show q1, q2, 1.0-q1-q2
    return (1.0-q1-q2)*CanonicalPRBox() + q1*LocalDeterministicBoxesCHSH(α=1, γ=0, β=0, λ=0) + q2*LocalDeterministicBoxesCHSH(α=1, γ=0, β=1, λ=0)
    #return c2*extremal_noise_generator(;extremal_noise_params...) + (1-c1-c2)*UniformRandomBox(scenario)
end

double_noisy_testbox = double_noisy_PRBox(q1=0.3, q2=0.05)

function W_BS09(n) # n is number of repetitions / batch size /copies of the wiring
    W = [0.0, 0.0, 1.0, 1.0,  # f_1(x, a_2) = x
         0.0, 0.0, 1.0, 1.0,  # g_1(y, b_2) = y
         0.0, 0.0, 0.0, 1.0,  # f_2(x, a_1) = a_1*x
         0.0, 0.0, 0.0, 1.0,  # g_2(y, b_1) = b_1*y
         0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0,  # f_3(x, a_1, a_2) = a_1 + a_2 mod 2
         0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0,] # g_3(y, b_1, b_2) = b_1 + b_2 mod 2

    return repeat(W, outer=[1, n])
end

BS09_testwiring = wirings.Wiring((2,2,2,2), Int.(W_BS09(1))[:,1])


(q1, q2, (1.0 - q1) - q2) = (0.3, 0.05, 0.6499999999999999)


Main.wirings.Wiring((2, 2, 2, 2), [0, 0, 1, 1, 0, 0, 1, 1, 0, 0  …  1, 0, 0, 1, 1, 0, 0, 1, 1, 0])

#### Benchmark direct computation wiring

In [9]:
testbox_fulljoint = nsboxes.reconstructFullJoint(double_noisy_testbox)

@btime direct_wired_box = wirings.direct_boxproduct(BS09_testwiring, testbox_fulljoint, testbox_fulljoint)
#nsboxes.NSBox((2,2,2,2),direct_wired_box)

  153.600 μs (5392 allocations: 85.98 KiB)


2×2×2×2 Array{Float64, 4}:
[:, :, 1, 1] =
 0.56125  0.0
 0.0      0.43875

[:, :, 2, 1] =
 0.4475   0.2275
 0.11375  0.21125

[:, :, 1, 2] =
 0.53    0.03125
 0.0325  0.40625

[:, :, 2, 2] =
 0.2375  0.4375
 0.325   0.0

#### Benchmark vectorized wiring product

In [10]:
testtorchbox = wirings.convert_nsjoint_to_matrixbox(nsboxes.reconstructFullJoint(double_noisy_testbox))

@btime wirings.vectorized_boxproduct(BS09_testwiring, testtorchbox, testtorchbox)
#nsboxes.NSBox((2,2,2,2), Float64.(vect_wired_box))	

  21.300 μs (530 allocations: 210.12 KiB)


2×2×2×2 Array{Float64, 4}:
[:, :, 1, 1] =
 0.56125  0.0
 0.0      0.43875

[:, :, 2, 1] =
 0.4475   0.2275
 0.11375  0.21125

[:, :, 1, 2] =
 0.53    0.03125
 0.0325  0.40625

[:, :, 2, 2] =
 0.2375  0.4375
 0.325   0.0

#### Benchmark tensorized code:

In [11]:
testmatrixbox = wirings.convert_nsjoint_to_matrixbox(nsboxes.reconstructFullJoint(double_noisy_testbox))

@btime wirings.tensorized_boxproduct(reshape(BS09_testwiring.wires, :, 1), testmatrixbox, testmatrixbox)
#NSBox((2,2,2,2), Float64.(tensor_wired_box))	

  73.000 μs (489 allocations: 57.72 KiB)


2×2×2×2×1 Array{Float64, 5}:
[:, :, 1, 1, 1] =
 0.56125  0.0
 0.0      0.43875

[:, :, 2, 1, 1] =
 0.4475   0.2275
 0.11375  0.21125

[:, :, 1, 2, 1] =
 0.53    0.03125
 0.0325  0.40625

[:, :, 2, 2, 1] =
 0.2375  0.4375
 0.325   0.0

#### Benchmark pycall torch code:

In [12]:
using PythonCall


#py"import AlgebraOfBoxesPy"
#@pyinclude("./AlgebraOfBoxesPy/utils.py") #ALready taken care of by evaluate.py 
ABP_eval = PythonCall.@py """include($(srcdir("AlgebraOfBoxesPy\\evaluate.py")))"""


Python: 'include(S:\\Sync\\University\\2023_MRP_2\\MRP2_WorkDir\\ABoxWorld\\src\\AlgebraOfBoxesPy\\evaluate.py)'

In [21]:
testbox_fulljoint = nsboxes.reconstructFullJoint(double_noisy_testbox)
n=1
W_torchvec = repeat(BS09_testwiring.wires, outer=[1, n])


#norm_count_mat = zeros(Int, 4, 4)
#for (a,b) in Iterators.product(0:1, 0:1)
#    for (x,y) in Iterators.product(0:1, 0:1)
#        norm_count_mat[2*x+y+1, 2*a+b+1] += (10*(y+1) + (x+1))
#    end
#end
# py"""PR_tensor = matrix_to_tensor(torch.tensor($norm_count_mat, dtype=torch.float64)).detach().numpy()"""


torch = pyimport("torch")
BoxProduct = @py """def BoxProduct(W,P,Q): return R_tensor(W,P,Q)[:,:,:,:,0]"""

tensorised_torchtestbox = torch.tensor(Py(testbox_fulljoint).to_numpy(), dtype=torch.float64)
tensorised_BS09_testwiring = torch.tensor(Py(W_torchvec).to_numpy(), dtype=torch.float64, requires_grad=true)


#py"""P = BoxProduct(tensorised_BS09_testwiring, tensorised_torchtestbox, tensorised_torchtestbox)"""
BoxProduct = @btime (@py """BoxProduct($tensorised_BS09_testwiring, $tensorised_torchtestbox, $tensorised_torchtestbox).detach().numpy()""")


  823.200 μs (1 allocation: 16 bytes)


Python: 'BoxProduct(tensor([[0.],\n        [0.],\n        [1.],\n        [1.],\n        [0.],\n        [0.],\n        [1.],\n        [1.],\n        [0.],\n        [0.],\n        [0.],\n        [1.],\n        [0.],\n        [0.],\n        [0.],\n        [1.],\n        [0.],\n        [1.],\n        [1.],\n        [0.],\n        [0.],\n        [1.],\n        [1.],\n        [0.],\n        [0.],\n        [1.],\n        [1.],\n        [0.],\n        [0.],\n        [1.],\n        [1.],\n        [0.]], dtype=torch.float64, requires_grad=True), tensor([[[[0.6750, 0.6250],\n          [0.3250, 0.0000]],\n\n         [[0.0000, 0.0500],\n          [0.0000, 0.3250]]],\n\n\n        [[[0.0000, 0.0000],\n          [0.3500, 0.6250]],\n\n         [[0.3250, 0.3250],\n          [0.3250, 0.0500]]]], dtype=torch.float64), tensor([[[[0.6750, 0.6250],\n          [0.3250, 0.0000]],\n\n         [[0.0000, 0.0500],\n          [0.0000, 0.3250]]],\n\n\n        [[[0.0000, 0.0000],\n          [0.3500, 0.6250]],\n\n    

In [48]:
timeit = pyimport("timeit")
@show 

# benchmark the task
#result = timeit.timeit("""R_tensor($(Py(tensorised_BS09_testwiring)), $(Py(tensorised_torchtestbox)), $(Py(tensorised_torchtestbox)))[:,:,:,:,0]""", setup="""include($(Py(srcdir("AlgebraOfBoxesPy\\evaluate.py"))))""", number=10)
# calculate the average
#average_result = pyconvert(Float64, result) / 10
# report the result
average_result = NaN
@info "Average time: $average_result seconds"


┌ Info: Average time: NaN seconds
└ @ Main s:\Sync\University\2023_MRP_2\MRP2_WorkDir\ABoxWorld\test\BenchmarkWirings.ipynb:10
